version: 0.2

# run-as: Linux-user-name

env:
  # shell: shell-tag
  # variables:
  #   key: "value"
  #   key: "value"
  # parameter-store:
  #   key: "value"
  #   key: "value"
  # exported-variables:
  #   - variable
  #   - variable
  # secrets-manager:
  #   key: secret-id:json-key:version-stage:version-id
  git-credential-helper: no 

# proxy:
#   upload-artifacts: no | yes
#   logs: no | yes

# batch:
#   fast-fail: false | true
#   # build-list:
#   # build-matrix:
#   # build-graph:
        
phases:
  install:
    # run-as: Linux-user-name
    on-failure: ABORT 
    # runtime-versions:
    #   runtime: version
    #   runtime: version
    commands:
      - yum update -y
    # finally:
    #   - command
    #   - command
  pre_build:
    # run-as: Linux-user-name
    on-failure: ABORT 
    commands:
      - echo " Zipping code for deployment "
      - zip package.zip *.py
    # finally:
    #   - command
    #   - command
  build:
    # run-as: Linux-user-name
    on-failure: ABORT 
    commands:
      - aws lambda update-function-code --function-name Aws-codepipeline-LambdaFunction-Di8ftGaOjXWA --zip-file fileb://package.zip
    # finally:
    #   - command
    #   - command
  post_build:
    # run-as: Linux-user-name
    on-failure: ABORT 
    commands:
      - echo " function code executed successfully "
#     finally:
#       - command
#       - command
# # reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
artifacts:
  files:
    - package.zip
  name: package-$(date +%Y-%m-%d) 
  # discard-paths: no | yes
  # base-directory: location
  # exclude-paths: excluded paths
  # enable-symlinks: no | yes
  s3-prefix: $(date +%Y)-$(date +%m)-$(date +%d)
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location
# # cache:
#   paths:
#     - path
#     - path
